/** Generated from the public Bearer routes. */
export const metadata = {
  "catalog_profile.create": {
    method: "post",
    path: "/api/v1/catalog-profiles",
    binary: false,
    "x-sdk-command": true,
  },
  "catalog_profile.list": {
    method: "get",
    path: "/api/v1/catalog-profiles",
    binary: false,
    "x-sdk-command": false,
  },
  "catalog_profile.update": {
    method: "patch",
    path: "/api/v1/catalog-profiles/{profileId}",
    binary: false,
    "x-sdk-command": true,
  },
  "catalog_presentation.update": {
    method: "patch",
    path: "/api/v1/catalog-presentations/{scopeId}",
    binary: false,
    "x-sdk-command": true,
  },
  "catalog_presentation.get": {
    method: "get",
    path: "/api/v1/catalog-presentations/{scopeId}",
    binary: false,
    "x-sdk-command": false,
  },
  "price_type.create": {
    method: "post",
    path: "/api/v1/price-types",
    binary: false,
    "x-sdk-command": true,
  },
  "price_type.update": {
    method: "patch",
    path: "/api/v1/price-types/{priceTypeId}",
    binary: false,
    "x-sdk-command": true,
  },
  "price_type.delete": {
    method: "delete",
    path: "/api/v1/price-types/{priceTypeId}",
    binary: false,
    "x-sdk-command": true,
  },
  "filter.create": {
    method: "post",
    path: "/api/v1/filters",
    binary: false,
    "x-sdk-command": true,
  },
  "filter.update": {
    method: "patch",
    path: "/api/v1/filters/{filterId}",
    binary: false,
    "x-sdk-command": true,
  },
  "filter.delete": {
    method: "delete",
    path: "/api/v1/filters/{filterId}",
    binary: false,
    "x-sdk-command": true,
  },
  "filter_value.create": {
    method: "post",
    path: "/api/v1/filters/{filterId}/values",
    binary: false,
    "x-sdk-command": true,
  },
  "filter_value.update": {
    method: "patch",
    path: "/api/v1/filters/{filterId}/values/{valueId}",
    binary: false,
    "x-sdk-command": true,
  },
  "filter_value.delete": {
    method: "delete",
    path: "/api/v1/filters/{filterId}/values/{valueId}",
    binary: false,
    "x-sdk-command": true,
  },
  "product.create": {
    method: "post",
    path: "/api/v1/products",
    binary: false,
    "x-sdk-command": true,
  },
  "product.update": {
    method: "patch",
    path: "/api/v1/products/{productId}",
    binary: false,
    "x-sdk-command": true,
  },
  "product.delete": {
    method: "delete",
    path: "/api/v1/products/{productId}",
    binary: false,
    "x-sdk-command": true,
  },
  "product_image.delete": {
    method: "delete",
    path: "/api/v1/products/{productId}/images/{imageId}",
    binary: false,
    "x-sdk-command": true,
  },
  "partner.create": {
    method: "post",
    path: "/api/v1/partners",
    binary: false,
    "x-sdk-command": true,
  },
  "partner.update": {
    method: "patch",
    path: "/api/v1/partners/{partnerId}",
    binary: false,
    "x-sdk-command": true,
  },
  "partner.delete": {
    method: "delete",
    path: "/api/v1/partners/{partnerId}",
    binary: false,
    "x-sdk-command": true,
  },
  "partner.resolve": {
    method: "post",
    path: "/api/v1/partners/resolve",
    binary: false,
    "x-sdk-command": true,
  },
  "organization.create": {
    method: "post",
    path: "/api/v1/organizations",
    binary: false,
    "x-sdk-command": true,
  },
  "organization.update": {
    method: "patch",
    path: "/api/v1/organizations/{organizationId}",
    binary: false,
    "x-sdk-command": true,
  },
  "organization.delete": {
    method: "delete",
    path: "/api/v1/organizations/{organizationId}",
    binary: false,
    "x-sdk-command": true,
  },
  "contract.create": {
    method: "post",
    path: "/api/v1/contracts",
    binary: false,
    "x-sdk-command": true,
  },
  "contract.update": {
    method: "patch",
    path: "/api/v1/contracts/{contractId}",
    binary: false,
    "x-sdk-command": true,
  },
  "contract.delete": {
    method: "delete",
    path: "/api/v1/contracts/{contractId}",
    binary: false,
    "x-sdk-command": true,
  },
  "custom_field.create": {
    method: "post",
    path: "/api/v1/custom-fields",
    binary: false,
    "x-sdk-command": true,
  },
  "custom_field.update": {
    method: "patch",
    path: "/api/v1/custom-fields/{fieldId}",
    binary: false,
    "x-sdk-command": true,
  },
  "custom_field.delete": {
    method: "delete",
    path: "/api/v1/custom-fields/{fieldId}",
    binary: false,
    "x-sdk-command": true,
  },
  "external_link.create": {
    method: "post",
    path: "/api/v1/external-links",
    binary: false,
    "x-sdk-command": true,
  },
  get_external_links: {
    method: "get",
    path: "/api/v1/external-links",
    binary: false,
    "x-sdk-command": false,
  },
  "warehouse.create": {
    method: "post",
    path: "/api/v1/warehouses",
    binary: false,
    "x-sdk-command": true,
  },
  "warehouse.update": {
    method: "patch",
    path: "/api/v1/warehouses/{warehouseId}",
    binary: false,
    "x-sdk-command": true,
  },
  "warehouse.delete": {
    method: "delete",
    path: "/api/v1/warehouses/{warehouseId}",
    binary: false,
    "x-sdk-command": true,
  },
  "purchase.create": {
    method: "post",
    path: "/api/v1/purchases",
    binary: false,
    "x-sdk-command": true,
  },
  "purchase.delete": {
    method: "delete",
    path: "/api/v1/purchases/{purchaseId}",
    binary: false,
    "x-sdk-command": true,
  },
  "procurement.create": {
    method: "post",
    path: "/api/v1/procurement/documents",
    binary: false,
    "x-sdk-command": true,
  },
  "procurement.update": {
    method: "patch",
    path: "/api/v1/procurement/documents/{documentId}",
    binary: false,
    "x-sdk-command": true,
  },
  "procurement.delete": {
    method: "delete",
    path: "/api/v1/procurement/documents/{documentId}",
    binary: false,
    "x-sdk-command": true,
  },
  "procurement.status": {
    method: "patch",
    path: "/api/v1/procurement/documents/{documentId}/status",
    binary: false,
    "x-sdk-command": true,
  },
  "procurement_import.retry": {
    method: "post",
    path: "/api/v1/procurement/imports/{importId}/recognize",
    binary: false,
    "x-sdk-command": true,
  },
  "procurement_import.reject": {
    method: "delete",
    path: "/api/v1/procurement/imports/{importId}",
    binary: false,
    "x-sdk-command": true,
  },
  "procurement_import.document": {
    method: "post",
    path: "/api/v1/procurement/imports/{importId}/document",
    binary: false,
    "x-sdk-command": true,
  },
  "procurement_payment.create": {
    method: "post",
    path: "/api/v1/procurement/payments",
    binary: false,
    "x-sdk-command": true,
  },
  "procurement_payment.update": {
    method: "patch",
    path: "/api/v1/procurement/payments/{paymentId}",
    binary: false,
    "x-sdk-command": true,
  },
  "procurement_payment.delete": {
    method: "delete",
    path: "/api/v1/procurement/payments/{paymentId}",
    binary: false,
    "x-sdk-command": true,
  },
  "procurement_payment.status": {
    method: "patch",
    path: "/api/v1/procurement/payments/{paymentId}/status",
    binary: false,
    "x-sdk-command": true,
  },
  "order.create": {
    method: "post",
    path: "/api/v1/orders",
    binary: false,
    "x-sdk-command": true,
  },
  "order.status": {
    method: "patch",
    path: "/api/v1/orders/{orderId}/status",
    binary: false,
    "x-sdk-command": true,
  },
  "order.reserve": {
    method: "patch",
    path: "/api/v1/orders/{orderId}/reservation",
    binary: false,
    "x-sdk-command": true,
  },
  "order.schedule": {
    method: "patch",
    path: "/api/v1/orders/{orderId}/schedule",
    binary: false,
    "x-sdk-command": true,
  },
  "order.delete": {
    method: "delete",
    path: "/api/v1/orders/{orderId}",
    binary: false,
    "x-sdk-command": true,
  },
  "sales_workflow.create": {
    method: "post",
    path: "/api/v1/sales-workflows",
    binary: false,
    "x-sdk-command": true,
  },
  "sales_workflow.update": {
    method: "patch",
    path: "/api/v1/sales-workflows/{workflowId}",
    binary: false,
    "x-sdk-command": true,
  },
  "sales_workflow.delete": {
    method: "delete",
    path: "/api/v1/sales-workflows/{workflowId}",
    binary: false,
    "x-sdk-command": true,
  },
  "order.transition": {
    method: "patch",
    path: "/api/v1/orders/{orderId}/transition",
    binary: false,
    "x-sdk-command": true,
  },
  "stock.receipt": {
    method: "post",
    path: "/api/v1/stock/receipt",
    binary: false,
    "x-sdk-command": true,
  },
  "stock.writeoff": {
    method: "post",
    path: "/api/v1/stock/writeoff",
    binary: false,
    "x-sdk-command": true,
  },
  "stock.transfer": {
    method: "post",
    path: "/api/v1/stock/transfer",
    binary: false,
    "x-sdk-command": true,
  },
  "settings.update": {
    method: "patch",
    path: "/api/v1/settings",
    binary: false,
    "x-sdk-command": true,
  },
  get_bootstrap: {
    method: "get",
    path: "/api/v1/bootstrap",
    binary: false,
    "x-sdk-command": false,
  },
  get_catalog: {
    method: "get",
    path: "/api/v1/catalog",
    binary: false,
    "x-sdk-command": false,
  },
  get_audit: {
    method: "get",
    path: "/api/v1/audit",
    binary: false,
    "x-sdk-command": false,
  },
  get_images_imageId_: {
    method: "get",
    path: "/api/v1/images/{imageId}",
    binary: false,
    "x-sdk-command": false,
  },
  get_procurement_imports: {
    method: "get",
    path: "/api/v1/procurement/imports",
    binary: false,
    "x-sdk-command": false,
  },
  "procurement_import.create": {
    method: "post",
    path: "/api/v1/procurement/imports",
    binary: true,
    "x-sdk-command": true,
  },
  get_procurement_imports_importId_file: {
    method: "get",
    path: "/api/v1/procurement/imports/{importId}/file",
    binary: false,
    "x-sdk-command": false,
  },
  "product_image.create": {
    method: "post",
    path: "/api/v1/products/{productId}/images",
    binary: true,
    "x-sdk-command": true,
  },
  "workspace.products.export": {
    method: "get",
    path: "/api/v1/workspace/products/export",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.products.list": {
    method: "get",
    path: "/api/v1/workspace/products",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.products.get": {
    method: "get",
    path: "/api/v1/workspace/products/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.partners.list": {
    method: "get",
    path: "/api/v1/workspace/partners",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.partners.get": {
    method: "get",
    path: "/api/v1/workspace/partners/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.orders.list": {
    method: "get",
    path: "/api/v1/workspace/orders",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.orders.get": {
    method: "get",
    path: "/api/v1/workspace/orders/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.lots.list": {
    method: "get",
    path: "/api/v1/workspace/lots",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.lots.get": {
    method: "get",
    path: "/api/v1/workspace/lots/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.purchases.list": {
    method: "get",
    path: "/api/v1/workspace/purchases",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.purchases.get": {
    method: "get",
    path: "/api/v1/workspace/purchases/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.procurementDocuments.list": {
    method: "get",
    path: "/api/v1/workspace/procurementDocuments",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.procurementDocuments.get": {
    method: "get",
    path: "/api/v1/workspace/procurementDocuments/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.procurementPayments.list": {
    method: "get",
    path: "/api/v1/workspace/procurementPayments",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.procurementPayments.get": {
    method: "get",
    path: "/api/v1/workspace/procurementPayments/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.movements.list": {
    method: "get",
    path: "/api/v1/workspace/movements",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.movements.get": {
    method: "get",
    path: "/api/v1/workspace/movements/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.warehouses.list": {
    method: "get",
    path: "/api/v1/workspace/warehouses",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.warehouses.get": {
    method: "get",
    path: "/api/v1/workspace/warehouses/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.organizations.list": {
    method: "get",
    path: "/api/v1/workspace/organizations",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.organizations.get": {
    method: "get",
    path: "/api/v1/workspace/organizations/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.contracts.list": {
    method: "get",
    path: "/api/v1/workspace/contracts",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.contracts.get": {
    method: "get",
    path: "/api/v1/workspace/contracts/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.priceTypes.list": {
    method: "get",
    path: "/api/v1/workspace/priceTypes",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.priceTypes.get": {
    method: "get",
    path: "/api/v1/workspace/priceTypes/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.filters.list": {
    method: "get",
    path: "/api/v1/workspace/filters",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.filters.get": {
    method: "get",
    path: "/api/v1/workspace/filters/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.customFields.list": {
    method: "get",
    path: "/api/v1/workspace/customFields",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.customFields.get": {
    method: "get",
    path: "/api/v1/workspace/customFields/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.salesWorkflows.list": {
    method: "get",
    path: "/api/v1/workspace/salesWorkflows",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.salesWorkflows.get": {
    method: "get",
    path: "/api/v1/workspace/salesWorkflows/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.catalogProfiles.list": {
    method: "get",
    path: "/api/v1/workspace/catalogProfiles",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.catalogProfiles.get": {
    method: "get",
    path: "/api/v1/workspace/catalogProfiles/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.replenishment.list": {
    method: "get",
    path: "/api/v1/workspace/replenishment",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.commissionReport.list": {
    method: "get",
    path: "/api/v1/workspace/commissionReport",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.commissionBalances.list": {
    method: "get",
    path: "/api/v1/workspace/commissionBalances",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.counterpartyBalances.list": {
    method: "get",
    path: "/api/v1/workspace/counterpartyBalances",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.stockPreview": {
    method: "get",
    path: "/api/v1/workspace/stock-preview",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.context": {
    method: "get",
    path: "/api/v1/workspace/context",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.summary": {
    method: "get",
    path: "/api/v1/workspace/summary",
    binary: false,
    "x-sdk-command": false,
  },
  "catalog_profile.catalog": {
    method: "get",
    path: "/api/v1/catalog-profiles/{profileId}/catalog",
    binary: false,
    "x-sdk-command": false,
  },
  "catalog_profile.product": {
    method: "get",
    path: "/api/v1/catalog-profiles/{profileId}/products/{productId}",
    binary: false,
    "x-sdk-command": false,
  },
  "events.list": {
    method: "get",
    path: "/api/v1/events",
    binary: false,
    "x-sdk-command": false,
  },
  "billing.overview": {
    method: "get",
    path: "/api/v1/billing",
    binary: false,
    "x-sdk-command": false,
  },
  "company.schema": {
    method: "get",
    path: "/api/v1/schema",
    binary: false,
    "x-sdk-command": false,
  },
} as const;
