/** Generated from the public Bearer routes. */
export const metadata = {
  "catalog_profile.list": {
    method: "get",
    path: "/api/v1/catalog-profiles",
    binary: false,
    "x-sdk-command": false,
  },
  "catalog_presentation.update": {
    method: "patch",
    path: "/api/v1/catalog-presentations/{scopeId}",
    binary: false,
    "x-sdk-command": true,
  },
  "catalog_presentation.get": {
    method: "get",
    path: "/api/v1/catalog-presentations/{scopeId}",
    binary: false,
    "x-sdk-command": false,
  },
  "product.create": {
    method: "post",
    path: "/api/v1/products",
    binary: false,
    "x-sdk-command": true,
  },
  "product.update": {
    method: "patch",
    path: "/api/v1/products/{productId}",
    binary: false,
    "x-sdk-command": true,
  },
  "product.delete": {
    method: "delete",
    path: "/api/v1/products/{productId}",
    binary: false,
    "x-sdk-command": true,
  },
  "product_image.delete": {
    method: "delete",
    path: "/api/v1/products/{productId}/images/{imageId}",
    binary: false,
    "x-sdk-command": true,
  },
  "partner.resolve": {
    method: "post",
    path: "/api/v1/partners/resolve",
    binary: false,
    "x-sdk-command": true,
  },
  "external_link.create": {
    method: "post",
    path: "/api/v1/external-links",
    binary: false,
    "x-sdk-command": true,
  },
  get_external_links: {
    method: "get",
    path: "/api/v1/external-links",
    binary: false,
    "x-sdk-command": false,
  },
  "order.create": {
    method: "post",
    path: "/api/v1/orders",
    binary: false,
    "x-sdk-command": true,
  },
  "order.status": {
    method: "patch",
    path: "/api/v1/orders/{orderId}/status",
    binary: false,
    "x-sdk-command": true,
  },
  "order.reserve": {
    method: "patch",
    path: "/api/v1/orders/{orderId}/reservation",
    binary: false,
    "x-sdk-command": true,
  },
  "order.schedule": {
    method: "patch",
    path: "/api/v1/orders/{orderId}/schedule",
    binary: false,
    "x-sdk-command": true,
  },
  "order.delete": {
    method: "delete",
    path: "/api/v1/orders/{orderId}",
    binary: false,
    "x-sdk-command": true,
  },
  "order.transition": {
    method: "patch",
    path: "/api/v1/orders/{orderId}/transition",
    binary: false,
    "x-sdk-command": true,
  },
  get_catalog: {
    method: "get",
    path: "/api/v1/catalog",
    binary: false,
    "x-sdk-command": false,
  },
  get_images_imageId_: {
    method: "get",
    path: "/api/v1/images/{imageId}",
    binary: false,
    "x-sdk-command": false,
  },
  "product_image.create": {
    method: "post",
    path: "/api/v1/products/{productId}/images",
    binary: true,
    "x-sdk-command": true,
  },
  "workspace.products.export": {
    method: "get",
    path: "/api/v1/workspace/products/export",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.products.list": {
    method: "get",
    path: "/api/v1/workspace/products",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.products.get": {
    method: "get",
    path: "/api/v1/workspace/products/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.orders.list": {
    method: "get",
    path: "/api/v1/workspace/orders",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.orders.get": {
    method: "get",
    path: "/api/v1/workspace/orders/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.salesWorkflows.list": {
    method: "get",
    path: "/api/v1/workspace/salesWorkflows",
    binary: false,
    "x-sdk-command": false,
  },
  "workspace.salesWorkflows.get": {
    method: "get",
    path: "/api/v1/workspace/salesWorkflows/{id}",
    binary: false,
    "x-sdk-command": false,
  },
  "catalog_profile.catalog": {
    method: "get",
    path: "/api/v1/catalog-profiles/{profileId}/catalog",
    binary: false,
    "x-sdk-command": false,
  },
  "catalog_profile.product": {
    method: "get",
    path: "/api/v1/catalog-profiles/{profileId}/products/{productId}",
    binary: false,
    "x-sdk-command": false,
  },
  "events.list": {
    method: "get",
    path: "/api/v1/events",
    binary: false,
    "x-sdk-command": false,
  },
  "company.schema": {
    method: "get",
    path: "/api/v1/schema",
    binary: false,
    "x-sdk-command": false,
  },
} as const;
